config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :users do
      member do
        post 'like'
        post 'dislike'
      end
    end
  
   resources :friends 

  resources :photos

  resources :chats

  resources :butts

  resources :gyms

  root to: "users#index"

end

app/models/friend.rb
class Friend < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :user

  @@daily_request_limit = 12
  # belongs_to :friend, :class_name => "User", :foreign_key => "friend_id"
  # has_enumerated :friendship_status, :class_name => 'FriendshipStatus', :foreign_key => 'friendship_status_id'

  # validates_presence_of   :friendship_status
  # validates_presence_of   :user
  # validates_presence_of   :friend
  # validates_uniqueness_of :friend_id, :scope => :user_id
  
#    validates_each :user_id do |record, attr, value|
#     record.errors.add attr, 'can not be same as friend' if record.user_id.eql?(record.friend_id)
#   end

#   def denied?
#     friendship_status.eql?(FriendshipStatus[:denied])
#   end

#   def pending?
#     friendship_status.eql?(FriendshipStatus[:pending])
#   end
  
#   def accepted?
#     friendship_status.eql?(FriendshipStatus[:accepted])
#   end

#   def notify_requester
#     UserNotifier.friendship_accepted(self).deliver
#   end

#   #show your most recent friends
#   def reverse
#     Friendship.where('user_id = ? and friend_id = ?', self.friend_id, self.user_id).first
#   end

# private
#   def set_pending
#     friendship_status_id = FriendshipStatus[:pending].id
#   end

#   scope :recent, lambda { order('friends.created_at DESC') }

#   def friend_to_be_requested
#   	@friend.all (except current user)
#   end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]

  # GET /friends
  # GET /friends.json

  def schedule
  end

  def really_like
  end

  def really_really_like
  end

  def best_friends
  end

  def index
    @friends = current_user.friends.all.order(:name).page(params[:page])
  end


  # GET /friends/1
  # GET /friends/1.json
  def show
    @user = current_user
    @friend = Friend.find(params[:id])
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friend_params
      params.require(:friend).permit(:name, :avatar, :like)
    end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_for(@friend) do |f| %>
  <% if @friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% @friend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :like %><br>
    <%= f.check_box :like %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render 'form' %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
  <h1>Listing friends</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Avatar</th>
      <th>Like</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <%= paginate @friends, :window => 1, :remote => true %>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.name %></td>
        <td><%= image_tag friend.avatar.url %></td>
        <td id = "like"><%= friend.like %></td>
        <td><%= link_to 'Show', user_friend_path(friend, current_user.id) %></td>
        <td><%= link_to 'Edit', edit_user_friend_path(friend, current_user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>





<h3>Swipe the green rectangle in the right direction to change its color:</h3>
<div class="box">

</div>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render 'form' %>

<%= link_to 'Back', friends_path %>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @friend.name %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @friend.avatar %>
</p>

<p>
  <strong>Like:</strong>
  <%= @friend.like %>
</p>

<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path %>