config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :users do
      member do
        post 'like'
        post 'dislike'
      end
    end
  
   resources :friends 

  resources :photos

  resources :chats

  resources :butts

  resources :gyms

  root to: "users#index"

end

app/models/butt.rb
class Butt < ActiveRecord::Base
end

app/controllers/butts_controller.rb
class ButtsController < ApplicationController
  before_action :set_butt, only: [:show, :edit, :update, :destroy]

  # GET /butts
  # GET /butts.json
  def index
    @butts = Butt.all
  end

  # GET /butts/1
  # GET /butts/1.json
  def show
  end

  # GET /butts/new
  def new
    @butt = Butt.new
  end

  # GET /butts/1/edit
  def edit
  end

  # POST /butts
  # POST /butts.json
  def create
    @butt = Butt.new(butt_params)

    respond_to do |format|
      if @butt.save
        format.html { redirect_to @butt, notice: 'Butt was successfully created.' }
        format.json { render :show, status: :created, location: @butt }
      else
        format.html { render :new }
        format.json { render json: @butt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /butts/1
  # PATCH/PUT /butts/1.json
  def update
    respond_to do |format|
      if @butt.update(butt_params)
        format.html { redirect_to @butt, notice: 'Butt was successfully updated.' }
        format.json { render :show, status: :ok, location: @butt }
      else
        format.html { render :edit }
        format.json { render json: @butt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /butts/1
  # DELETE /butts/1.json
  def destroy
    @butt.destroy
    respond_to do |format|
      format.html { redirect_to butts_url, notice: 'Butt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_butt
      @butt = Butt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def butt_params
      params.require(:butt).permit(:name, :location, :fart, :shape, :percentbodysize)
    end
end

app/helpers/butts_helper.rb
module ButtsHelper
end

app/views/butts/_form.html.erb
<%= form_for(@butt) do |f| %>
  <% if @butt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@butt.errors.count, "error") %> prohibited this butt from being saved:</h2>

      <ul>
      <% @butt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :fart %><br>
    <%= f.check_box :fart %>
  </div>
  <div class="field">
    <%= f.label :shape %><br>
    <%= f.text_field :shape %>
  </div>
  <div class="field">
    <%= f.label :percentbodysize %><br>
    <%= f.text_field :percentbodysize %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/butts/edit.html.erb
<h1>Editing butt</h1>

<%= render 'form' %>

<%= link_to 'Show', @butt %> |
<%= link_to 'Back', butts_path %>

app/views/butts/index.html.erb
<h1>Listing butts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Fart</th>
      <th>Shape</th>
      <th>Percentbodysize</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @butts.each do |butt| %>
      <tr>
        <td><%= butt.name %></td>
        <td><%= butt.location %></td>
        <td><%= butt.fart %></td>
        <td><%= butt.shape %></td>
        <td><%= butt.percentbodysize %></td>
        <td><%= link_to 'Show', butt %></td>
        <td><%= link_to 'Edit', edit_butt_path(butt) %></td>
        <td><%= link_to 'Destroy', butt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Butt', new_butt_path %>

app/views/butts/new.html.erb
<h1>New butt</h1>

<%= render 'form' %>

<%= link_to 'Back', butts_path %>

app/views/butts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @butt.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @butt.location %>
</p>

<p>
  <strong>Fart:</strong>
  <%= @butt.fart %>
</p>

<p>
  <strong>Shape:</strong>
  <%= @butt.shape %>
</p>

<p>
  <strong>Percentbodysize:</strong>
  <%= @butt.percentbodysize %>
</p>

<%= link_to 'Edit', edit_butt_path(@butt) %> |
<%= link_to 'Back', butts_path %>